# Generated by Django 4.2.18 on 2025-02-23 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0002_symptom_remove_moodlog_symptoms_moodlog_symptoms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ['-date'], 'verbose_name': 'Mood Log', 'verbose_name_plural': 'Mood Logs'},
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Mood Log'),
            preserve_default=False,
        ),
    ]
