# Generated by Django 4.2.18 on 2025-02-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0003_alter_moodlog_options_remove_moodlog_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name'], 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AddField(
            model_name='moodlog',
            name='medications',
            field=models.ManyToManyField(blank=True, help_text='Select medications taken today', to='mood_tracker.medication', verbose_name='Medications Taken'),
        ),
    ]
