# Generated by Django 4.2.18 on 2025-02-23 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0004_alter_medication_options_moodlog_medications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterModelOptions(
            name='moodlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mood Log', 'verbose_name_plural': 'Mood Logs'},
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='date',
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='medications',
        ),
        migrations.AddField(
            model_name='moodlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time of Logging'),
            preserve_default=False,
        ),
    ]
