# Generated by Django 4.2.18 on 2025-02-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0005_alter_medication_options_alter_moodlog_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.AlterField(
            model_name='moodlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
