# Generated by Django 4.2.18 on 2025-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechEmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(choices=[('angry', 'Angry'), ('disgust', 'Disgust'), ('fear', 'Fear'), ('happy', 'Happy'), ('ps', 'Pleasant Surprise'), ('sad', 'Sad'), ('neutral', 'Neutral')], max_length=20)),
            ],
            options={
                'verbose_name': 'Speech Emotion Log',
                'verbose_name_plural': 'Speech Emotion Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
